spring:
  application:
    name: ProjetoGestaoFinanceira-BackEnd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestaofinanceira?useTimezone=true&serverTimezone=UTC
    username: root
    password: Co123456789
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
jwt:
  secret: c2VjcmV0LW11aXRvLXNlZ3VyYS1jb20tMzItYnl0ZXM=
  expiration:
    ms: 86400000