spring:
  application:
    name: ProjetoGestaoFinanceira-BackEnd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestaofinanceira?useTimezone=true&serverTimezone=UTC
    username: root
    password: Co123456789
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      #dialect: org.hibernate.dialect.MySQLDialect A própia IDE pede para não deixar esta linha para evitar Warning
    show-sql: false
    open-in-view: false